package dev.bloc

import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json

/**
 * A [Bloc] subclass that automatically persists its state to [HydratedStorage] on every
 * [emit] and restores it the next time the Bloc is instantiated.
 *
 * ### Setup
 * Assign the storage backend **once** at app startup before any HydratedBloc is created:
 * ```kotlin
 * class App : Application() {
 *     override fun onCreate() {
 *         super.onCreate()
 *         HydratedBloc.storage = SharedPreferencesStorage(this)
 *     }
 * }
 * ```
 *
 * ### Usage
 * ```kotlin
 * @Serializable
 * data class CounterState(val count: Int = 0)
 *
 * class CounterBloc : HydratedBloc<CounterState, CounterEvent>(
 *     initialState = CounterState(),
 *     serializer  = CounterState.serializer(),
 * ) {
 *     init {
 *         on<CounterEvent.Increment> { _, emit -> emit(state.copy(count = state.count + 1)) }
 *         on<CounterEvent.Decrement> { _, emit -> emit(state.copy(count = state.count - 1)) }
 *     }
 * }
 * ```
 * The count now survives app restarts with no extra code.
 *
 * ### Storage key
 * Defaults to the class simple name (e.g. `"CounterBloc"`). Override for a stable,
 * refactor-proof key:
 * ```kotlin
 * override val storageKey get() = "counter_v2"
 * ```
 *
 * ### Resetting state
 * | Method | Storage | In-memory state | Use case |
 * |---|---|---|---|
 * | [clearStoredState] | Deleted | Unchanged | Wipe storage; visible next launch |
 * | [resetToInitialState] | Deleted + re-written with `initialState` | Set immediately | Instant full reset |
 *
 * ### Custom storage (e.g. for tests)
 * ```kotlin
 * val bloc = CounterBloc(storage = InMemoryStorage())
 * ```
 *
 * @param S State type — must be annotated with `@Serializable`.
 * @param E Event type.
 * @param initialState Fallback used when no persisted data is found.
 * @param serializer kotlinx.serialization serializer for [S].
 *   Use `MyState.serializer()` (generated by the `@Serializable` annotation).
 * @param storage Storage backend. Defaults to [HydratedBloc.storage].
 */
abstract class HydratedBloc<S : Any, E : Any>(
    initialState: S,
    private val serializer: KSerializer<S>,
    /**
     * Storage key for this Bloc's persisted state.
     * Pass `null` (the default) to use the class simple name automatically.
     * Pass an explicit string for a stable, refactor-proof key:
     * ```kotlin
     * class CounterBloc : HydratedBloc<CounterState, CounterEvent>(
     *     initialState    = CounterState(),
     *     serializer      = CounterState.serializer(),
     *     storageKeyParam = "counter_v2",
     * )
     * ```
     *
     * **Why a constructor param instead of `open val`?**
     * `init` blocks run before subclass property initializers, so an `open val`
     * overridden in a subclass would still be `null` when `restore()` is called.
     * A constructor parameter is resolved before any `init` block executes.
     */
    storageKeyParam: String? = null,
    private val storage: HydratedStorage = HydratedBloc.storage,
) : Bloc<S, E>(initialState), AnyHydratedBloc {

    /** Saved for [resetToInitialState]. */
    private val _initialState: S = initialState

    /**
     * The key under which this Bloc's state is persisted.
     * Resolved at construction time to avoid the leaking-this trap with `open val`.
     */
    val storageKey: String = storageKeyParam ?: this::class.simpleName ?: "HydratedBloc"

    /**
     * Guards against re-persisting state during the initial restore pass.
     * Starts `false`; set to `true` only after restoration completes.
     */
    private var persistEnabled = false

    init {
        // Attempt to restore previously-persisted state.
        // `persistEnabled` is still false here, so the emit inside restore()
        // won't trigger a redundant write back to storage.
        restore()
        // Enable normal persistence for all subsequent emits.
        persistEnabled = true
    }

    // -------------------------------------------------------------------------
    // Emit — intercept for persistence
    // -------------------------------------------------------------------------

    /**
     * Emits [nextState] to the state stream **and** persists it to [storage].
     *
     * Persistence is skipped during the initial restore pass to avoid a
     * redundant write of data that was just read.
     */
    override fun emit(nextState: S) {
        super.emit(nextState)
        if (persistEnabled && !isClosed) persist(nextState)
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    private fun restore() {
        try {
            val bytes = storage.read(storageKey) ?: return
            val restored = Json.decodeFromString(serializer, bytes.decodeToString())
            // Only emit if the restored value differs from initialState, so that
            // fresh installs don't fire an unnecessary onChange.
            if (restored != state) emit(restored)
        } catch (_: Exception) {
            // Corrupted or schema-incompatible data — silently keep initialState.
        }
    }

    private fun persist(state: S) {
        try {
            val json = Json.encodeToString(serializer, state)
            storage.write(storageKey, json.encodeToByteArray())
        } catch (e: Exception) {
            addError(BlocError("HydratedBloc: failed to persist state for '$storageKey'", e))
        }
    }

    // -------------------------------------------------------------------------
    // Public reset API
    // -------------------------------------------------------------------------

    /**
     * Deletes the persisted state without changing the current in-memory state.
     * The next app launch will start from [initialState].
     */
    override fun clearStoredState() {
        storage.delete(storageKey)
    }

    /**
     * Deletes the persisted state **and** immediately emits [initialState],
     * resetting the UI right now without restarting the app.
     */
    override fun resetToInitialState() {
        storage.delete(storageKey)
        emit(_initialState)
    }

    // -------------------------------------------------------------------------
    // Companion
    // -------------------------------------------------------------------------

    companion object {
        /**
         * App-wide storage singleton. Assign at startup:
         * ```kotlin
         * HydratedBloc.storage = SharedPreferencesStorage(context)
         * ```
         * Defaults to [InMemoryStorage] so unit tests work without an Android context.
         */
        var storage: HydratedStorage = InMemoryStorage()

        /**
         * Clears **all** stored state in one call.
         * Equivalent to "log out and reset everything".
         */
        fun clearAll() = storage.clear()
    }
}
